In [1]:
import numpy as np

c:\users\meraj\appdata\local\programs\python\python37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\meraj\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\users\meraj\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
list = [1,2,3,4,5,6,7,8,9]
arr = np.array(list)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(list2)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
#Accessing Elements
print(matrix[1][2]) # First Method
print(matrix[1,2]) # Second Method

6
6


In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [11]:
print(np.zeros((5,5)))
print(np.ones((4,3)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# create 5 random numbers between 0 and 1
np.random.random(5)

array([0.79177275, 0.70831282, 0.78956473, 0.14960726, 0.83079282])

In [13]:
# create an integer random number between 0 and 10
np.random.randint(0,10)

5

In [21]:
# create 15 random numbers between 0 and 40
array = np.random.randint(0,40,15)
print(array)

[29 20  4  8 12  7 35 13 12  2  9 22 23 25  2]


In [52]:
# Generate Same Random Number Again and Again
np.random.seed(0) # any number can be used in place of 0
np.random.randint(100)

44

In [3]:
np.random.seed(0)
arr = np.random.randn(4,3)
arr

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351]])

In [51]:
array.argmax() # returns index of maximum value in array

6

In [40]:
len(array)

15