### Criteria For Reshape
**The New Shape should be compatible with the original shape**


Resape dimensions product must be equal to Original Shape dimensions product

In [1]:
import numpy as np

c:\users\meraj\appdata\local\programs\python\python37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\meraj\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\users\meraj\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)


In [10]:
np.random.seed(0)
arr = np.random.randn(2,3)
arr

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788]])

In [11]:
arr.shape

(2, 3)

In [14]:
print(arr.reshape(3,2))
print()
print(arr.reshape(6,1))
print()
print(arr.reshape(1,6))

[[ 1.76405235  0.40015721]
 [ 0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788]]

[[ 1.76405235]
 [ 0.40015721]
 [ 0.97873798]
 [ 2.2408932 ]
 [ 1.86755799]
 [-0.97727788]]

[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788]]


**Numpy allow us to give one of new shape parameter as -1**  
**eg: (2,-1) or (-1,3) but not (-1, -1).**

It simply means that it is an unknown dimension and we want numpy to figure it out. And numpy will figure this by looking at the **'length of the array and remaining dimensions'** and making sure it satisfies the above mentioned criteria.

if we try to provide both dimension as unknown i.e new shape as (-1,-1). It will throw an error

In [19]:
arr.reshape(-1) 

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788])

In [21]:
# We have provided column as 1 but rows as unknown
arr.reshape(-1,1)

array([[ 1.76405235],
       [ 0.40015721],
       [ 0.97873798],
       [ 2.2408932 ],
       [ 1.86755799],
       [-0.97727788]])

In [23]:
# Here rows unknown but column as 2
arr.reshape(-1,2)

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788]])

In [25]:
# Here row as 1 but column as unknown
arr.reshape(1,-1)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788]])